app = "competa-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sh -c 'node_modules/.bin/drizzle-kit migrate && node_modules/.bin/tsx src/infra/database/seeds/index.ts'"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  BETTER_AUTH_URL = "https://api.competa.com.br"
  WEB_URL = "https://app.competa.com.br"
  EMAIL_FROM = "nao-responda@competa.com.br"
  SENTRY_DSN = "https://2b1c69fcc04db10e5c05fc2d04f3ea42@o4512068933189632.ingest.us.sentry.io/4512068942954496"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    path = "/health"
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
